<?php

namespace AppBundle\Repository;

/**
 * BorrowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BorrowRepository extends \Doctrine\ORM\EntityRepository
{

    public function getListAboToday()
    {
        $qb = $this->createQueryBuilder('r');
        $qb->select('r');
        $qb->from('Reader', 'r');
        $qb->where('r.dateAbonnement = :today');
        $qb->setParameter('today', new \DateTime(), \Doctrine\DBAL\Types\Type::DATETIME);
    }
}
