<?php

namespace AppBundle\Repository;

/**
 * ReaderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReaderRepository extends \Doctrine\ORM\EntityRepository
{
}
